# Generated by Django 5.2.17 on 2026-09-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_residency_adminaccount_booking_residency_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="adminverificationcode",
            table="admin_verification",
        ),
        migrations.AlterModelTable(
            name="booking",
            table="booking_details",
        ),
        migrations.AlterModelTable(
            name="room",
            table="room_details",
        ),
    ]
