# Generated by Django 5.2.17 on 2026-09-28 05:24

import django.db.models.deletion
from django.db import migrations, models


def copy_admin_residencies(apps, schema_editor):
    AdminAccount = apps.get_model("booking", "AdminAccount")
    database = schema_editor.connection.alias
    for admin in AdminAccount.objects.using(database).all():
        admin.residencies.add(admin.residency_id)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_room_room_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("ROOM", "Room"),
                            ("BEDROOM", "Bedroom"),
                            ("BATHROOM", "Bathroom"),
                            ("PARKING", "Parking"),
                            ("RECEPTION", "Reception"),
                            ("DINING", "Dining area"),
                            ("LOBBY", "Lobby"),
                            ("EXTERIOR", "Exterior"),
                            ("AMENITIES", "Amenities"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AdminVerificationCode",
        ),
        migrations.AddField(
            model_name="adminaccount",
            name="residencies",
            field=models.ManyToManyField(
                blank=True, related_name="admins", to="booking.residency"
            ),
        ),
        migrations.RunPython(copy_admin_residencies, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="adminaccount",
            name="residency",
        ),
        migrations.AddField(
            model_name="residency",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="residency",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="residency",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="residencies/"),
        ),
        migrations.AddField(
            model_name="residency",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="residency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="booking.residency",
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="booking.room",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("residency__isnull", False), ("room__isnull", True)),
                    models.Q(("residency__isnull", True), ("room__isnull", False)),
                    _connector="OR",
                ),
                name="gallery_image_has_one_parent",
            ),
        ),
    ]
