# Generated by Django 5.2.17 on 2026-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("GPAY", "Google Pay"),
                    ("PHONEPE", "PhonePe"),
                    ("PAYTM", "Paytm"),
                    ("CARD", "Card"),
                    ("NET_BANKING", "Net banking"),
                ],
                default="GPAY",
                max_length=15,
            ),
        ),
    ]
