# Generated by Django 5.2.17 on 2026-09-26 07:56

import django.db.models.deletion
from django.db import migrations, models


def assign_legacy_residency(apps, schema_editor):
    Residency = apps.get_model("booking", "Residency")
    Room = apps.get_model("booking", "Room")
    Booking = apps.get_model("booking", "Booking")
    residency, _ = Residency.objects.get_or_create(
        residency_name="Legacy Residency",
        defaults={
            "provider_name": "Staywise",
            "location": "Unassigned",
            "description": "Existing rooms migrated from the original booking system.",
        },
    )
    Room.objects.filter(residency__isnull=True).update(residency_id=residency.pk)
    Booking.objects.filter(residency__isnull=True).update(residency_id=residency.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_room_inventory_booking_quantity_admin_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Residency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residency_name", models.CharField(max_length=150, unique=True)),
                ("provider_name", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "residency",
                "ordering": ["residency_name"],
            },
        ),
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "residency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admins",
                        to="booking.residency",
                    ),
                ),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="residency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.residency",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="residency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="booking.residency",
            ),
        ),
        migrations.RunPython(assign_legacy_residency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="room",
            name="residency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="booking.residency",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="residency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.residency",
            ),
        ),
    ]
