# Generated by Django 5.2.17 on 2026-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_adminverificationcode_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("residency", "room_number"),
                name="room_number_unique_per_residency",
            ),
        ),
    ]
